services:

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_DATACENTER: ${CASSANDRA_DATACENTER}
      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra_logs:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local'" ]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  cassandra_logs: