services:
  mongodb:
    image: mongo:8.0
    container_name: assessment_db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodb_archive:/data/db
      - ./scripts/mongosh:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD","mongosh","mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/admin?authSource=admin","--eval","db.runCommand({ connectionStatus: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 20