services:
  mongodb:
    image: mongo:8.0
    container_name: assessment_db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodb_archive:/data/db
      - ./scripts/mongosh:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand({ ping: 1 })" ]
      interval: 5s
      timeout: 3s
      retries: 20

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./scripts/datasources:/datasources
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
    depends_on:
      mongodb:
          condition: service_healthy


