services:
  mongodb:
    image: mongo:8.0
    container_name: assessment_db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./datasources:/datasources
      - ./mongodb_archive:/data/db
    ports:
      - ${MONGO_PORT}

volumes:
  mongodb_archive: