services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${ADMIN_USER}
      MYSQL_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_logs:/var/lib/mysql
      - ./scripts/ddl:/docker-entrypoint-initdb.d

