import os
BOOTSTRAP_SERVERS = os.getenv('BOOTSTRAP_SERVERS')
CASSANDRA_HOST = os.getenv('CASSANDRA_HOST')
CASSANDRA_KEYSPACE = os.getenv('CASSANDRA_KEYSPACE')
CASSANDRA_PORT = os.getenv('CASSANDRA_PORT')
CASSANDRA_TABLE = os.getenv('CASSANDRA_TABLE')
KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS')
KAFKA_TOPIC = os.getenv('KAFKA_TOPIC')
WIKIPEDIA_ENDPOINT = os.getenv('WIKIPEDIA_ENDPOINT')

